version: '3.7'
services:
  docker-image-update_jupyterhub:
    build:
        context: ./
        dockerfile: Dockerfile
        args:
          TAG: ${TAG}
    env_file:
      - .env
    image: ucphhpc/docker-image-updater
    deploy:
      mode: global
      placement:
          constraints:
              - "node.role==manager"
    environment:
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -interval 60