services:
  updater:
    build: ./
    image: ucphhpc/docker-image-updater:${TAG}
    deploy:
      mode: global
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: -interval 10