services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile
    image: ucphhpc/docker-image-updater:${TAG}
    deploy:
      mode: global
    environment:
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: -interval 10