version: '3.7'
services:
  updater:
    build:
        context: ./
        dockerfile: Dockerfile
        args:
          TAG: ${TAG}
    env_file:
      - .env
    image: ucphhpc/docker-image-updater
    deploy:
      mode: global
    environment:
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -interval 10